name: windml
channels:
- defaults
- conda-forge
dependencies:
- basemap=1.0.7
- certifi=2016.2.28
- cycler=0.10.0
- freetype=2.5.5=2
- geos=3.5.0=0
- icu=54.1=0
- jbig=2.1=0
- jpeg=9b=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- matplotlib=2.0.2
- mkl=2017.0.3=0
- numpy=1.13.1
- olefile=0.44
- openssl=1.0.2l=0
- pillow=4.2.1
- pip=9.0.1
- pyparsing=2.2.0
- pyqt=5.6.0
- python>=2.7
- python-dateutil=2.6.1
- python.app=1.2
- pytz=2017.2
- qt=5.6.2=2
- readline=6.2=2
- scipy=0.19.1
- setuptools=36.4.0
- sip=4.18
- six=1.10.0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - scikit-learn==0.19.0
  - windml==0.5.0


